# Generated by Django 2.0.7 on 2021-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default="none"),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="none", max_length=30),
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(default="none", max_length=30),
        ),
    ]
