# Generated by Django 2.0.7 on 2021-06-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
        ('tasks', '0004_auto_20210617_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiles.Tile'),
        ),
    ]
