# Generated by Django 2.0.7 on 2021-06-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_tileid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tileId',
            new_name='tile',
        ),
    ]
