# Generated by Django 2.0.7 on 2021-06-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launchDate', models.DateField()),
                ('status', models.CharField(choices=[('live', 'LIVE'), ('pending', 'PENDING'), ('archive', 'ARCHIVE')], max_length=1)),
            ],
        ),
    ]
