# Generated by Django 2.0.7 on 2021-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[('live', 'LIVE'), ('pending', 'PENDING'), ('archive', 'ARCHIVE')], max_length=7),
        ),
    ]
